## Put comments here that give an overall description of what your
## functions do

## The function makeCacheMatrix will create a special matrix returning a list of functions to
## 1. get the value of the matrix
## 2. set the value of the matrix
## 3. get the inverse of the matrix from the cache
## 4. set the inverse of the matrix, passed as parameter, into the cache.

makeCacheMatrix <- function(x = matrix()) {
        ## setting the inverse value to NULL to accept a new matrix
        i <- NULL 
        ## Defining the set function to pass in different inputs without needing to recreate the speacial matrix.
        set <- function(y){
                ## Pushing the matrix value into cache.
                x <<- y
                ## resetting the inverse to NULL to accept the new matrix of values.
                i <- NULL 
        }
        ## Reading the data in the special matrix created by the function.
        get <- function() x 
        ## push the value of inverse into cache.
        setInverse <- function(inv) i <<- inv 
        ## get the inverse value from cache.
        getInverse <- function() i 
        ## generate a list of functions that will help cacheSolve function pull inverse from the cache as appropriate.
        list(set = set, get = get, setInverse = setInverse, getInverse = getInverse) 
}


## The function cacheSolve will calculate the inverse of a matrix. 
## If the inverse is cached, then it will retrieve the calculation from the cache.
## The parameter 'x' to this function is the special list object generated by makeCacheMatrix function above.

cacheSolve <- function(x, ...) {
        ## get the inverse from the cache
        i <- x$getInverse()
        ## Check if the inverse retreived from cache is NULL
        if (!is.null(i)){
                ## Print message to indicate that the function is returning
                ## data from the cache.
                message("getting cached data")
                ## exit the function with the value from the cache.
                return(i)
        }
        ## if there was no data in the cache then compute the inverse.
        ## Get the data that was passed into the special matrix.
        data <- x$get()
        ## calculate the inverse of the data in the special matrix.
        i <- solve(data)
        ## push the calculation to the cache.
        x$setInverse(i)
        # return the calculated inverse value.
        i         
}
